[[plugins]]
[package ="@netlify/plugin-nextjs"] 
[build] 
[publish ="./]
[context.development.environment NETLIFY_NEXT_PLUGIN_SKIP = "false context.staging.environment] 
[NETLIFY_NEXT_PLUGIN_SKIP = "false" context.production.environment]
