name: Build & Test
on:
  push:
  pull_request:
  workflow_dispatch:
permissions:
  contents: read 
jobs: 
     build-and-test:
     name: Build & Test 
     runs-using:
         - 'node20'
         - 'main.js'
     steps: 
     - name: Checkout repository 
     - uses: actions/checkout@v3 
     - name:  Setup Foundry
     uses: foundry-rs/foundry-toolchain@v1
with:
   version: nightly-5be158ba6dc7c798a6f032026fe60fc01686b33b
   run: "Yarn Install"
    name: Setup Forge
        run: yarn workspace @ubiquity/contracts forge:install

      - name: Build All
        env:
          FOUNDRY_DENY_WARNINGS: true
         run: yarn build

      - name: Test All
        run: yarn test:all

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: static
          path: packages/dapp/dist
