name: Yarn Audit
on:
  pull_request:
  push:
jobs:
  audit-and-fix:
    name: Audit & Fix
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.10.0"
      - run: | 
               yarn-audit-fix
